# site properties and page defaults
title: The Health-related Water Microbiology Lab
subtitle: Department of Civil and Environmental Engineering
description: Study microbioal Water Quality using molecular genetic tools and bioinformatics tools; Aiming to conduct open science research
   #An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
# header: images/icon.png
# footer: images/MisRiver.HEIC
# proofer: false
logo: /assets/img/HWu.jpg
# site social media and other links
links:
  email: huiyun.wu@wsu.edu
  orcid: 0000-0001-8935-7759
  google-scholar: sAIJSssAAAAJ
  github: wuhuiyun07
  # website:
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

theme: jekyll-theme-minimal